services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Tokyo
      CHANNEL_SECRET: ${CHANNEL_SECRET}
      CHANNEL_ACCESS_TOKEN: ${CHANNEL_ACCESS_TOKEN}
      MY_USER_ID: ${MY_USER_ID}
      NS_MARIADB_USER: ${NS_MARIADB_USER}
      NS_MARIADB_PASSWORD: ${NS_MARIADB_PASSWORD}
      NS_MARIADB_HOSTNAME: ${NS_MARIADB_HOSTNAME}
      NS_MARIADB_PORT: ${NS_MARIADB_PORT}
      NS_MARIADB_DATABASE: ${NS_MARIADB_DATABASE}
    depends_on:
      mariadb: 
        condition: service_healthy

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - 5050:80
    depends_on:
      - mariadb