name: Deploy to GCE

on:
  # push:
  #   # branches:
  #   #   - main
  workflow_dispatch:

jobs:
  build:
    name: Build Go Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Build
        run: |
          make build

      - name: Set up dotenvx
        run: curl -sfS https://dotenvx.sh/install.sh | sh

      - name: Decrypt .env
        run: |
          DOTENV_PRIVATE_KEY=${{ secrets.DOTENV_PRIVATE_KEY }} dotenvx decrypt .env

      - name: Change ports
        run: |
          sed -i 's/8080/80/g' .env

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Stop Application
        run: |
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone=${{ secrets.GCP_INSTANCE_ZONE }} --command="sudo systemctl stop reminder.service"

      - name: Copy Binary and Environment Variables to GCE
        run: |
          gcloud compute scp main ${{ secrets.GCP_INSTANCE_NAME }}:~/reminder --zone=${{ secrets.GCP_INSTANCE_ZONE }} --quiet
          gcloud compute scp .env ${{ secrets.GCP_INSTANCE_NAME }}:~/.env --zone=${{ secrets.GCP_INSTANCE_ZONE }} --quiet

      - name: Set up Permissions
        run: |
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone=${{ secrets.GCP_INSTANCE_ZONE }} --command="chmod 755 ~/reminder"
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone=${{ secrets.GCP_INSTANCE_ZONE }} --command="sudo /sbin/setcap 'cap_net_bind_service=+ep' ~/reminder"

      - name: Start Application
        run: |
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone=${{ secrets.GCP_INSTANCE_ZONE }} --command="sudo systemctl start reminder.service"
